const express = require('express');
const cors = require('cors');
const app = express();  
app.use(cors());
app.use(express.json());
app.get('/', (req, res) => {res.send('Study Buddy Finder API')});
app.listen(5000, () => console.log('Server is running on port 5000'));
const authRoutes = require('./routes/auth');
app.use('/api/auth', authRoutes);
const profileRoutes = require('./routes/profiles');
app.use('/api/profiles', profileRoutes);